### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GiulianoBeltrami** [GiulianoBeltrami/totvs-desafio#1]
- [x] Banco
   - [x] banco automatizado
   - [x] tabela automática migrations

- [x] Registro
   - [x] Get todos usuários com status code e erro
   - [x] Post criar usuário com status code e erro
   - [x] Colocar GUID como ID

- [x] Login
   - [x] rota autentificar usuário
   - [x] Gerar token de login

- [x] Testes
   - [x] registro
   - [x] login

- [ ] Criar documentação no readme
